config/routes.rb
BillionBits::Application.routes.draw do

  scope "(:locale)", locale: /pt|en/ do
    root to: 'home_pages#home'

    match 'index', to: "home_pages#home", :as => 'home_page'
    match '', to: "home_pages#home"

    match 'about', to: 'home_pages#about', via: 'get'
    match 'contact', to: 'home_pages#contact', via: 'get'
    match 'home', to: 'home_pages#home', via: 'get'

    resources :users
    resources :sessions
    match "/signup", to: 'users#new', :as => 'register'
    match "/login", to: 'sessions#new', via: 'get'
    match "/logout", to: 'sessions#destroy'

    resources :games
    match "/game/new", to: 'games#new', :as => 'add_games'
    match "/game/add_bits", to: 'games#add_bits', :as => 'add_bits', via: 'post'
    match "/game/remove_bits", to: 'games#remove_bits', :as => 'remove_bits', via: 'post'

  end

  root to: 'home_pages#home'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :rate

  has_and_belongs_to_many :profiles
  has_and_belongs_to_many :likes, :class_name => "Profile", :join_table => "profiles_games_like", :association_foreign_key => "profile_id"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :bio, :birthday, :name, :user_id

  belongs_to :user
  has_and_belongs_to_many :games
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  
  attr_accessor :password
  attr_accessible :email, :username,
                  :password, :password_confirmation
  accepts_nested_attributes_for :profile
  attr_accessible :profile_attributes

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false },
                    length: { within: 5..50 },
                    format: { with: VALID_EMAIL_REGEX }

  validates :username, uniqueness: { case_sensitive: false },
                    length: { within: 4..20 }

  validates :password, confirmation: true,
                       length: { within: 4..50 },
                       presence: true,
                       if: :password_required?

  before_save {
    email.downcase!
  }



  before_save :encrypt_new_password


  def self.authenticate(email_or_username, password)
    user = find_by_email(email_or_username)
    if not user
      user = find_by_username(email_or_username)
    end

    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected

  def encrypt_new_password
    return if password.blank?
    self.hashed_password = encrypt(password)
  end

  def password_required?
    hashed_password.blank? || password.present?
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  before_filter :set_locale
 
  def set_locale
    logger.debug "SET LOCALE: #{locale}\n"
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => ((I18n.locale == I18n.default_locale) ? nil : I18n.locale) }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    authenticate
    @game = Game.new
  end

  def create
    # Só permite se estiver logado
    authenticate

    @game = Game.new(params[:game])
    current_user.profile.games << @game

    if current_user.save
      flash[:success] = "Jogo criado com sucesso"
      redirect_to current_user
    else
      render :action => 'new'
    end
  end

  def edit
    authenticate

    @game = Game.find(params[:id])
  end

  def update
    authenticate

    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      redirect_to user_path(current_user), :notice => "Atributos atualizados"
    else
      render :action => 'edit'
    end
  end

  def add_bits
    # Somente ajax
    render :root_path if not request.xhr?
    # Somente se logado
    authenticate

    game = Game.find(params[:id])
    game.likes << current_user.profile unless game.likes.include?(current_user.profile)
    
    if not game.save!
      flash[:error] = "Erro ao salvar bit"
    end

    render :text => game.likes.count
  end

  def remove_bits
    puts "="*100
    # Somente ajax
    render :root_path if not request.xhr?
    # Somente se logado
    authenticate

    game = Game.find(params[:id])
    
    if game.likes.include?(current_user.profile)
      game.likes.delete(current_user.profile)
    end
    
    if not game.save!
      flash[:error] = "Erro ao salvar bit"
    end

    render :text => game.likes.count
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      flash[:success] = 'Você entrou.'
      redirect_to root_path
    else
      flash[:alert] = 'Combinação invalida'
      render :action => 'new'
    end
  end

  def destroy
    reset_session
    flash[:alert] = 'Você saio.'
    redirect_to root_url, :error => "Você saio"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(params[:user])
    @user.profile.update_attributes(params[:user][:profile])
    # Autosave and rollback profile
    if @user.save
      flash[:success] = "Sua conta foi criada"
      redirect_to @user
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_path, :notice => "Atributos atualizados"
    else
      render :action => 'edit'
    end
  end

  def show
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Não foi possivel encontrar usuário"
      redirect_to :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title)
    base_title = "Billion Bits"
    if page_title.empty?
      base_title
    else
      "#{base_title}" + " | " + "#{page_title}"
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def authenticate
    logged_in? ? true : access_denied
  end

  def logged_in?
    current_user.is_a? User
  end

  def access_denied
    redirect_to login_path, :notice => "Entre para accessar a página" and return false
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/games/edit.html.erb
<% provide(:current, t('pages.edit game') ) %>
<h1><%= t('pages.edit game') %></h1>

<div class="row">
  <div class="span6 offset3">
    <% @object = @game %>
    <%= form_for(@game) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.submit "Update game", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<% provide(:current, t('pages.games') ) %>
<h1><%= t('pages.games') %></h1>

<div class="row">
  <div class="span6 offset3">
    <% @object = @game %>
    <%= form_for(@game) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.submit "Create game", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/home_pages/about.html.erb
<% provide(:current, t('pages.about')) %>
<h1><%= t('pages.about') %></h1>
<div class="container">
    <hr class="game-divider">

      <div class="row-fluid">

        <div class="span7">
          <h1 class="game-heading">Guilherme Fay Vergara</h1>
          <h2 class="muted">Universidade de Brasília</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ultrices sapien ut nulla dapibus, sit amet porta turpis faucibus. Aenean lobortis lectus nibh, a viverra metus scelerisque quis. Quisque mollis malesuada urna, id convallis ipsum bibendum ut. Donec a elit purus. Aliquam viverra arcu sit amet risus cursus aliquam. Donec quam ante, faucibus sed ipsum vel, scelerisque ornare quam. Morbi mollis ligula aliquet urna tempor porttitor. Maecenas nisl sem, pulvinar eget enim ac, ornare adipiscing mauris. Curabitur auctor hendrerit odio, non placerat quam interdum a. Vestibulum lectus augue, vulputate in molestie at, pulvinar nec neque. Sed leo augue, tincidunt at ultricies eu, dapibus ut lectus. Integer vehicula arcu sem, a tincidunt tellus porttitor pulvinar.
        </div>
        <div class="span1"></div>
        <div class="span4">
          <%=image_tag 'home_icon2.png', :class => "img-polaroid"%>
        </div>
      </div>

      <hr class="game-divider">

      <div class="row-fluid">
        <div class="span1"></div>
        <div class="span4">
          <%=image_tag 'home_icon2.png', :class => "img-polaroid"%>
        </div>


        <div class="span7">
          <h1 class="game-heading">Gustavo Jaruga Cruz</h1>
          <h2 class="muted">Universidade de Brasília</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu porttitor arcu. Nullam tristique nibh et odio hendrerit, in semper purus sollicitudin. Fusce rhoncus elit sed sollicitudin tristique. Fusce lorem lacus, dapibus sed lorem nec, tempor fringilla nunc. Etiam sit amet dapibus turpis. Sed quis sem scelerisque, gravida urna et, sagittis dui. Nulla molestie augue pulvinar ipsum fringilla varius. Ut euismod porta rhoncus. Etiam venenatis ullamcorper eros, pellentesque tempor nisi tincidunt porttitor.
          </p>
        </div>
        
      </div>

      <hr class="game-divider">

      <div class="row fluid">

        <div class="span7">
          <h1 class="game-heading">Marcos Ronaldo Pereira Junior</h1>
          <h2 class="muted">Universidade de Brasília</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at nisi sed mi vulputate convallis. Morbi mattis ipsum odio, vitae pellentesque orci ullamcorper ac. Duis tincidunt vel est vitae fringilla. Proin eget faucibus nunc. Nulla porttitor nunc metus. Aenean a ipsum erat. Morbi varius turpis suscipit risus tincidunt, eget dignissim tortor scelerisque. Suspendisse malesuada pulvinar orci eu scelerisque. Nulla aliquet lacus laoreet quam consectetur pellentesque. Nulla at nibh elit. Maecenas gravida, neque vitae mattis vestibulum, nisl leo pellentesque nisi, ut aliquet nisi lectus at urna. Donec aliquam est vel ullamcorper laoreet. Sed dapibus, odio ac semper consectetur, ligula dolor consequat urna, vel aliquet magna quam vel eros. Aliquam erat volutpat. Maecenas eu est eget urna faucibus pretium.
          </p>
        </div>
        <div class="span1"></div>
        <div class="span4">
          <%=image_tag 'home_icon2.png', :class => "img-polaroid"%>
        </div>
      </div>

</div>

app/views/home_pages/contact.html.erb
<% provide(:current, t('pages.contact')) %>


<div class="container">
  <h1><%= t('pages.contact') %></h1>
    
  <hr class="game-divider">

  <div class="row-fluid">
    <div class="span1"></div>
    <div class="span4">
      <%=image_tag 'home_icon2.png', :class => "img-polaroid"%>
    </div>

    <div class="span7">
      <h1 class="game-heading">Billion Bits Games</h1>
      <h2 class="muted">Universidade de Brasília</h2>
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu porttitor arcu. Nullam tristique nibh et odio hendrerit, in semper purus sollicitudin. Fusce rhoncus elit sed sollicitudin tristique. Fusce lorem lacus, dapibus sed lorem nec, tempor fringilla nunc. Etiam sit amet dapibus turpis. Sed quis sem scelerisque, gravida urna et, sagittis dui. Nulla molestie augue pulvinar ipsum fringilla varius. Ut euismod porta rhoncus. Etiam venenatis ullamcorper eros, pellentesque tempor nisi tincidunt porttitor.
      </p>
    </div>
      
  </div>

   

  <hr class="game-divider">

      <h1><%= t('pages.team') %></h1>

      <div class="row-fluid">

        <div class="span4">
          <div style="text-align: center">
            <%=image_tag 'fay.jpg', :class => "img-polaroid"%>
          </div>
          <h1 class="name-heading">Guilherme Fay Vergara</h1>
          <h2 class="muted">Universidade de Brasília</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ultrices sapien ut nulla dapibus, sit amet porta turpis faucibus. Aenean lobortis lectus nibh, a viverra metus scelerisque quis. Quisque mollis malesuada urna, id convallis ipsum bibendum ut. Donec a elit purus. Aliquam viverra arcu sit amet risus cursus aliquam. Donec quam ante, faucibus sed ipsum vel, scelerisque ornare quam. Dapibus sed lorem nec, tempor fringilla nunc. Etiam sit amet dapibus turpis. Sed quis sem scelerisque, gravida urna et, sagittis dui. Nulla molestie augue pulvinar ipsum fringilla varius. Ut euismod porta rhoncus. Etiam venenatis ullamcorper eros, pellentesque tempor nisi tincidunt porttitor.
        </div>
        <div class="span4">
          <div style="text-align: center">
            <%=image_tag 'gust.jpg', :class => "img-polaroid"%>
          </div>
          <h1 class="name-heading">Gustavo Jaruga Cruz</h1>
          <h2 class="muted">Universidade de Brasília</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ultrices sapien ut nulla dapibus, sit amet porta turpis faucibus. Aenean lobortis lectus nibh, a viverra metus scelerisque quis. Quisque mollis malesuada urna, id convallis ipsum bibendum ut. Donec a elit purus. Aliquam viverra arcu sit amet risus cursus aliquam. Donec quam ante, faucibus sed ipsum vel, scelerisque ornare quam. Morbi mollis ligula aliquet urna tempor porttitor. Maecenas nisl sem, pulvinar eget enim ac, ornare adipiscing mauris. Curabitur auctor hendrerit odio, non placerat quam interdum a. Vestibulum lectus augue, vulputate in molestie at, pulvinar nec neque. Sed leo augue, tincidunt at ultricies eu, dapibus ut lectus. Integer vehicula arcu sem, a tincidunt tellus porttitor pulvinar.
        </div>
        <div class="span4">
          <div style="text-align: center">
            <%=image_tag 'marcos.jpg', :class => "img-polaroid"%>
          </div>
          <h1 class="name-heading">Marcos Ronaldo Pereira Junior</h1>
          <h2 class="muted">Universidade de Brasília</h2>
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum at nisi sed mi vulputate convallis. Morbi mattis ipsum odio, vitae pellentesque orci ullamcorper ac. Duis tincidunt vel est vitae fringilla. Proin eget faucibus nunc. Nulla porttitor nunc metus. Aenean a ipsum erat. Morbi varius turpis suscipit risus tincidunt, eget dignissim tortor scelerisque. Suspendisse malesuada pulvinar orci eu scelerisque. Nulla aliquet lacus laoreet quam consectetur pellentesque. Nulla at nibh elit. Maecenas gravida, neque vitae mattis vestibulum, nisl leo pellentesque nisi, ut aliquet nisi lectus at urna. Donec aliquam est vel ullamcorper laoreet. Sed dapibus, odio ac semper consectetur, ligula dolor consequat urna, vel aliquet magna quam vel eros. Aliquam erat volutpat. Maecenas eu est eget urna faucibus pretium.
        </div>
      </div>

   

</div>

app/views/home_pages/home.html.erb
<% provide(:current, t('pages.home')) %>
<div class="container">
<div class="center hero-unit">
  <h1><%= t('home.welcome') %></h1>

  <h2>
    <%= t('home.welcome_text_html') %>
  </h2>

  <%= link_to t('home.sign_up'), '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      &copy; BillionBits 2014
    </small>

    <nav>
      <ul>
        <li>
          <%= link_to t('pages.about'), about_path %></li>
        <li>
          <%= link_to t('pages.contact'), contact_path %></li>
        <li>  
          <%= link_to t('pages.home'), home_path %></li>
      </ul>

  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar-wrapper">
  <div class="container">
    <div class="navbar navbar-static-top navbar-inverse">
      <div class="navbar-inner">
          
          <%= link_to root_path, class: "brand", id: "logo" do %>
              <!-- <%= image_tag('home_icon.png') %> --> Billion Bits Games
          <% end %>
          <nav>
            <ul class="nav pull-left divider-vertical">
              <li <% if yield(:current) == t('pages.home') %>class="active"<% end %>>
                <%= link_to t('pages.home'), home_path %></li>
              <li <% if yield(:current) == t('pages.about') %>class="active"<% end %>>
                <%= link_to t('pages.about'), about_path %></li>
              <li <% if yield(:current) == t('pages.contact') %>class="active"<% end %>>
                <%= link_to t('pages.contact'), contact_path %></li>
              
              <% if logged_in? %>
                <li class="active"> <%= link_to current_user.email, current_user %> </li>
              <% else %>
                <li <% if yield(:current) == t('pages.login') %>class="active"<% end %>>
                  <%= link_to t('pages.login'), login_path %></li>
                <li <% if yield(:current) == t('pages.register') %>class="active"<% end %>>
                  <%= link_to t('pages.register'), register_path %></li>
              <% end %>
            
            </ul>
            <div class="btn-group pull-right">
                <% if I18n.locale == :en %> 
                  <%= link_to "English",  {locale: :en}, :class => "btn active" %>
                <% else %>
                  <%= link_to "English",  {locale: :en}, :class => "btn" %>
                <% end %>

                <% if I18n.locale == :pt %> 
                  <%= link_to "Português",  {locale: ((I18n.locale == I18n.default_locale) ? nil : I18n.default_locale)}, :class => "btn active" %>
                <% else %>
                  <%= link_to "Português",  {locale: ((I18n.locale == I18n.default_locale) ? nil : I18n.default_locale)}, :class => "btn" %>
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_like_button.html.erb
<% if game.likes.include?(current_user.profile) %>
  <%= link_to 'Remove bit', remove_bits_path(:id => game), method: 'post', remote: 'true',
                          id: "remove_bits_#{game.id}", class: "btn btn-small btn-danger" %>
<% else %>
  <%= link_to 'Add bit', add_bits_path(:id => game), method: 'post', remote: 'true',
                          id: "add_bits_#{game.id}", class: "btn btn-small btn-success" %>
<% end %>

<% content_for :js do %>

  add_game_<%= game.id %> = function(xhr, data){
      var btn = $('#add_bits_<%= game.id %>')[0];
      btn.href = '<%= remove_bits_path(:id => game) %>';
      btn.innerHTML = 'Remove bit';
      btn.id = btn.id.replace("add_bits_", "remove_bits_");
      btn.className = btn.className.replace("success", "danger");
      $('#game_bits_<%= game.id %>').text(data.responseText);
      $('#remove_bits_<%= game.id %>').unbind('ajax:complete')
      $('#remove_bits_<%= game.id %>').bind('ajax:complete',remove_game_<%= game.id %>);
  }

  remove_game_<%= game.id %> = function(xhr, data){
      var btn = $('#remove_bits_<%= game.id %>')[0];
      btn.href = '<%= add_bits_path(:id => game) %>';
      btn.innerHTML = 'Add bit';
      btn.id = btn.id.replace("remove_bits_", "add_bits_");
      btn.className = btn.className.replace("danger", "success");
      $('#game_bits_<%= game.id %>').text(data.responseText);
      $('#add_bits_<%= game.id %>').unbind('ajax:complete')
      $('#add_bits_<%= game.id %>').bind('ajax:complete', add_game_<%= game.id %>);
  }
  
  $('#add_bits_<%= game.id %>').bind('ajax:complete', add_game_<%= game.id %>);
  $('#remove_bits_<%= game.id %>').bind('ajax:complete',remove_game_<%= game.id %>);
<% end %> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:current)) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>

  <script type="text/javascript">
    <%= yield :js %>
  </script>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:current, t('pages.edit profile') ) %>
<h1><%= t('pages.edit profile') %></h1>

<div class="row">
  <div class="span6 offset3">
    <% @object = @user %>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.fields_for :profile do |ff| %>
          <%= ff.label :name %>
          <%= ff.text_field :name %>
      <% end %>

      <%= f.label :username %>
      <%= f.text_field :username %>
      
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Update account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:current, t('pages.register') ) %>
<h1><%= t('pages.register') %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.fields_for :profile do |ff| %>
          <%= ff.label :name %>
          <%= ff.text_field :name %>
      <% end %>

      <%= f.label :username %>
      <%= f.text_field :username %>
      
      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:current, @user.email) %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        Nome: <%= @user.profile.name %>
        Username: <%= @user.username %>
        Mail: <%= @user.email %>
      </h1>
    </section>

  </aside>

</div>

<div class="row">
  <div class="span4">
  <% if logged_in? %>
    <%= link_to t('pages.logout'), logout_path, class: "btn btn-medium btn-primary"  %>
    <%= link_to t('pages.add games'), add_games_path, class: "btn btn-medium btn-primary"  %>
    <%= link_to t('pages.edit profile'), edit_user_path(current_user), class: "btn btn-medium btn-primary"  %>
  <% end %>
  </div>
</div>

<div class="border-row">
    <div class="box-content down"></div>
</div>

<h1 class = "game-header"> Seus Jogos </h1>
<% if @user.profile.games.empty? %>
    <div class = "game-area">
      <center>
        <h2 class="game-title"> Sem jogos </h2>
      </center>
    </div> <!-- Game area -->
<% end %>

<% @user.profile.games.each do |game| %>
  <div class = "game-area">
    <h2 class="game-title"> <%= game.name %> </h2>
    <p class="game-text"> <%= game.rate %> </p>
    <!-- tag e de empty, placeholder para pegar id -->
    <h4><%= t("Bits: ") %><e id= <%= "game_bits_#{game.id}" %>><%= game.likes.count %></e></h4>
    <% if logged_in? %>
      <%= render 'layouts/like_button', :game => game %>
      <%= link_to 'Edit', edit_game_path(game), class: "btn btn-small btn-primary" %>
    <% end %>
  </div> <!-- Game area -->
<% end %>